### ISSUE TITLE
Orientation 6 and 8 in test folder are swapped.

### ISSUE THREAD

**Issue by TonyBrobston** [ginpei/exif-orientation#17]
If I'm understanding correctly, based on this exif orientation explanation:
![image](https://user-images.githubusercontent.com/4724577/88306074-e2960300-cccf-11ea-99d1-03d1c36794e3.png)
Orientation 6 is rotated 45 degrees counter-clockwise and orientation 8 is rotated 45 degrees clockwise.

However, the orientation 6 image seems to be rotated 45 degrees clockwise:
<img src="https://raw.githubusercontent.com/ginpei/exif-orientation/master/test/090-6.jpg" />

..and orientation 8 image seems to be rotated 45 counter-clockwise:
<img src="https://raw.githubusercontent.com/ginpei/exif-orientation/master/test/270-8.jpg" />

**Comment by TonyBrobston** [comment]
So to clarify, the orientation in the exif is correct, but I think the direction the image is turned is incorrect. This doesn't matter in the grand scheme of things.

**Comment by ginpei** [comment]
@TonyBrobston Hi thank you for asking it.

In my understanding, the explanation you shared should represent ORIGINAL graphic data instead of the image rotated in print.

According to the following URL, the code 6 rotates clockwise.

- https://www.impulseadventure.com/photo/exif-orientation.html

![image](https://user-images.githubusercontent.com/355808/88343518-711d7b00-ccf6-11ea-9abc-852b217b6269.png)

Also, the specification document says on page 30:

- https://home.jeita.or.jp/tsc/std-pdf/CP3451C.pdf

> 1 = The 0th row is at the visual top of the image, and the 0th column is the visual left-hand side.
> 6 = The 0th row is the visual right-hand side of the image, and the 0th column is the visual top.
